### ISSUE TITLE
Launcher keeps crashing.

### ISSUE THREAD

**Issue by Wukkel4** [elmfrain/parkourhelper#2]
Today I downloaded the parkour recorder mod and I wanted to try it out in single player. The recording and saving works fine but when I press P it says on the top right waiting for player but soon after my game just crashes. Why is this happening? Do I need to install anything besides to mod to get it to work?

**Comment by elmfrain** [comment]
No you don't. I had another user tell me that it crashes too due to similar circumstances (this case, most likely a critical rendering bug). I had recently updated the mod that changes how the everything renders in this mod; I'd suggest trying the latest version of the mod.

**Comment by elmfrain** [comment]
This have been fixed since update v1.1.0.0
