### ISSUE TITLE
parkour_recorder-1.1.2.0-1.12.2 Load not the Changelog

### ISSUE THREAD

**Issue by Titoo8899** [elmfrain/parkourhelper#5]
hi,
I have look your mod and it works fine. But only one think will not load and say Offline Changelog.

Look the Picture and I hope you can fix it. It is not bad for your mod the mod works only then People will the Chancelog ingame show work it not for the newest Update
![2022-03-12_10 33 03](https://user-images.githubusercontent.com/42325138/158012722-51b64230-a64a-4b9f-a6df-d3457781c302.png)

**Comment by elmfrain** [comment]
Hello!
In the update v1.1.2.0, the changelog is fetched online. However, since I am not very familiar with networking (downloading from online and stuff) the code I wrote for it may not be good.

Nevertheless, I will look into it, and I really appreciate you bringing this to my attention!
